#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : compat-double-conversion-soname1
Version  : 3.1.1
Release  : 25
URL      : https://github.com/google/double-conversion/archive/v3.1.1.tar.gz
Source0  : https://github.com/google/double-conversion/archive/v3.1.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: compat-double-conversion-soname1-lib = %{version}-%{release}
Requires: compat-double-conversion-soname1-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-scons
Patch1: 0001-Change-CMake-build-to-use-the-same-SONAME-as-the-Sco.patch
Patch2: 0002-Use-GNUInstallDirs-to-install-files-in-the-expected-.patch

%description
https://github.com/google/double-conversion
This project (double-conversion) provides binary-decimal and decimal-binary
routines for IEEE doubles.

%package lib
Summary: lib components for the compat-double-conversion-soname1 package.
Group: Libraries
Requires: compat-double-conversion-soname1-license = %{version}-%{release}

%description lib
lib components for the compat-double-conversion-soname1 package.


%package license
Summary: license components for the compat-double-conversion-soname1 package.
Group: Default

%description license
license components for the compat-double-conversion-soname1 package.


%prep
%setup -q -n double-conversion-3.1.1
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1564677061
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake .. -DBUILD_SHARED_LIBS:BOOL=ON -DINSTALL_LIB_DIR=/usr/lib64
make  %{?_smp_mflags} VERBOSE=1
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test || :

%install
export SOURCE_DATE_EPOCH=1564677061
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-double-conversion-soname1
cp COPYING %{buildroot}/usr/share/package-licenses/compat-double-conversion-soname1/COPYING
cp LICENSE %{buildroot}/usr/share/package-licenses/compat-double-conversion-soname1/LICENSE
pushd clr-build
%make_install
popd
## Remove excluded files
rm -f %{buildroot}/usr/include/double-conversion/bignum.h
rm -f %{buildroot}/usr/include/double-conversion/cached-powers.h
rm -f %{buildroot}/usr/include/double-conversion/diy-fp.h
rm -f %{buildroot}/usr/include/double-conversion/double-conversion.h
rm -f %{buildroot}/usr/include/double-conversion/fast-dtoa.h
rm -f %{buildroot}/usr/include/double-conversion/fixed-dtoa.h
rm -f %{buildroot}/usr/include/double-conversion/ieee.h
rm -f %{buildroot}/usr/include/double-conversion/strtod.h
rm -f %{buildroot}/usr/include/double-conversion/utils.h
rm -f %{buildroot}/usr/lib64/cmake/double-conversion/double-conversionConfig.cmake
rm -f %{buildroot}/usr/lib64/cmake/double-conversion/double-conversionConfigVersion.cmake
rm -f %{buildroot}/usr/lib64/cmake/double-conversion/double-conversionTargets-relwithdebinfo.cmake
rm -f %{buildroot}/usr/lib64/cmake/double-conversion/double-conversionTargets.cmake
rm -f %{buildroot}/usr/lib64/libdouble-conversion.so

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/libdouble-conversion.so.1
/usr/lib64/libdouble-conversion.so.1.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/compat-double-conversion-soname1/COPYING
/usr/share/package-licenses/compat-double-conversion-soname1/LICENSE
